#!/bin/sh

export GOPATH=$PWD
export GOMAXPROCS=1

# Abort on errors after this point ...
set -e

# Make sure the app builds
./build || exit $?

# Run the tests
echo ""
echo ".................................................................."
echo "Running tests ...................................................."
echo ".................................................................."
echo ""

go test -v . -bench=".*" || exit $?

echo ""
echo ".................................................................."
echo "Finished tests ..................................................."
echo ".................................................................."
echo ""
